version: '3.6'
services:
    nodejs:
        container_name: project_angular
        image: 'node:latest'
        
        working_dir: /home/node/app
        command:
            - /bin/sh
            - '-c'
            - 'npm install && ./node_modules/.bin/ng serve --host 0.0.0.0'
        ports:
            - '4200:4200'
        volumes:
            - './src/twitter-front-app/.:/home/node/app'
        networks:
            - my-network

networks:
  my-network:
    driver: bridge